In [1]:
!pip install psycopg2

Collecting psycopg2
  Downloading https://files.pythonhosted.org/packages/d1/1e/b450599a27b1809bccbd4e369f397cb18dc56b875778d961f9ae180b54b7/psycopg2-2.9.3.tar.gz (380kB)
     |████████████████████████████████| 389kB 5.8MB/s eta 0:00:01
Installing collected packages: psycopg2
  Running setup.py install for psycopg2 ... done
Successfully installed psycopg2-2.9.3
WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [2]:
!pip install pandas

Collecting pandas
  Using cached https://files.pythonhosted.org/packages/47/a5/79156a83c133b5d049a38f444e11eacabab8b3ad00814d8c6811fe9850e2/pandas-1.4.2-cp38-cp38-macosx_10_9_x86_64.whl
Collecting numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" (from pandas)
  Using cached https://files.pythonhosted.org/packages/64/4a/b008d1f8a7b9f5206ecf70a53f84e654707e7616a771d84c05151a4713e9/numpy-1.22.3.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/gaurnitai/Desktop/Programming/Python/DataScience/yt/py-database/dsenv/lib/python3.8/site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Using cached https://files.pythonhosted.org/packages/60/2e/dec1cc18c51b8df33c7c4d0a321b084cf38e1733b98f9d15018880fb4970/pytz-2022.1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.5 in /Users/gaurnitai/Desktop/Programming/Python/DataScience/yt/py-database/dsenv/lib/python3.8/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... done
  Created wheel for numpy: filename=numpy-1.22.3-cp38-cp38-macosx_10_12_x86_64.whl size=5818944 sha256=18b57fd5e80402860265e87e96b7a36b02293c10044ae61eb9912ecf1b02af66
  Stored in directory: /Users/gaurnitai/Library/Caches/pip/wheels/21/37/10/81a13af5964837a3627457192fbc14d926b1a2dcd810f70fbf
Successfully built numpy
Installing collected packages: numpy, pytz, pandas
Successfully installed numpy-1.22.3 pandas-1.4.2 pytz-2022.1
WARNING: You are using pip version 19.2.3, however version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [3]:
import psycopg2 as pg
import pandas as pd

In [5]:
survey_public_df = pd.read_csv('../data/survey_results_public.csv')

In [6]:
survey_schema_df = pd.read_csv('../data/survey_results_schema.csv')

In [8]:
survey_public_df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [9]:
survey_schema_df.head()

        Column                                       QuestionText
0   Respondent  Randomized respondent ID number (not in order ...
1   MainBranch  Which of the following options best describes ...
2     Hobbyist                            Do you code as a hobby?
3  OpenSourcer        How often do you contribute to open source?
4   OpenSource  How do you feel about the quality of open sour...

In [19]:
# Lets drop some of the survey_schema_df columns
columns_to_delete = survey_public_df.loc[:, 'UndergradMajor':]

In [21]:
survey_public_df.drop(columns=columns_to_delete, axis=1, inplace=True)

In [22]:
survey_public_df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G..."
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)"
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)"
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)"
...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)"

In [29]:
#conn = pg.connect(host=hostname, port=port, user=username, password=password)

In [62]:
# Lets wrap in try except to handle any connection error
def connect_to_db(hostname, port, username, password):
    try:
        conn = pg.connect(host=hostname, port=port, user=username, password=password)
    except OperationError as e:
        raise e
    else:
        print('Connected Successfully....')
    return conn

In [73]:
hostname='localhost'
port='5433'
username='gaurnitai'
password='superuser'
database='gaurnitai'
conn=None

In [74]:
conn = connect_to_db(hostname, port, username, password)

Connected Successfully....

In [75]:
# Now lets create cursor to run sql query and fetch the result from database
curr = conn.cursor()

In [76]:
# Get column names from csv
survey_public_df.columns

Index(['respondent', 'mainbranch', 'hobbyist', 'opensourcer', 'opensource',
       'employment', 'country', 'student', 'edlevel'],
      dtype='object')

In [77]:
def rename_columns(column):
    col = column.replace(' ','')
    return col.lower()

In [78]:
survey_public_df.columns.map(rename_columns)

Index(['respondent', 'mainbranch', 'hobbyist', 'opensourcer', 'opensource',
       'employment', 'country', 'student', 'edlevel'],
      dtype='object')

In [79]:
survey_public_df.columns = survey_public_df.columns.map(rename_columns)
survey_public_df.columns

Index(['respondent', 'mainbranch', 'hobbyist', 'opensourcer', 'opensource',
       'employment', 'country', 'student', 'edlevel'],
      dtype='object')

In [80]:
# CREATE TABLE to export csv data to table
def create_table(curr):
    create_table_command = ('''
        CREATE TABLE IF NOT EXISTS survey_public (
        respondent INTEGER PRIMARY KEY, 
        mainbranch VARCHAR(255) NOT NULL, 
        hobbyist VARCHAR(255) NOT NULL, 
        opensourcer VARCHAR(255) NULL,  
        opensource VARCHAR(255) NULL,
        employment VARCHAR(255) NULL, 
        country VARCHAR(255) NULL, 
        student VARCHAR(255) NULL, 
        edlevel VARCHAR(255) NULL
        )
    ''')
    curr.execute(create_table_command)

In [81]:
create_table(curr)
conn.commit()

In [82]:
# Now lets export data from csv to database
# Here are two use cases possible
# 1. Record may already exist - Update operation
# 2. New record need to be enter - Insert operation
for i, row in survey_public_df.iterrows():
    if check_if_data_exists():
        update_row()
    else:
        insert_row()

NameError: name 'check_if_data_exists' is not defined

In [85]:
def check_if_data_exists(curr, respondent_id):
    query = ("""SELECT video_id FROM VIDEOS WHERE video_id = %s""")
    curr.execute(query, (respondent_id))
    return curr.fetchone() is not None

In [89]:
def update_row(curr, respondent, mainbranch, hobbyist, opensourcer, 
               opensource,employment, country, student, edlevel):
    query = ("""UPDATE survey_public 
    SET mainbranch=%s,
        hobbyist=%s,
        opensourcer = %s,
        opensource = %s,
        employment = %s,
        country = %s,
        student = %s,
        edlevel = %s 
        WHERE respondent=%s;
    """)
    row_to_update = (mainbranch, hobbyist, opensourcer, 
               opensource,employment, country, student, edlevel, respondent)
    curr.execute(curr, row_to_update)

In [ ]:
def insert_row(curr, respondent, mainbranch, hobbyist, opensourcer, 
               opensource,employment, country, student, edlevel):
    query = ("""INSERT INTO survey_public (mainbranch, hobbyist, opensourcer, 
               opensource,employment, country, student, edlevel)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s);""")
    row_to_insert = (mainbranch, hobbyist, opensourcer, 
               opensource,employment, country, student, edlevel)
    curr.execute(query, row_to_insert)